// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrROB1SHKgJqPbIY2S2Qm7pKz4bwPAVY',
    appId: '1:304338530315:web:6ce80d8c321151eee9570e',
    messagingSenderId: '304338530315',
    projectId: 'smartmart-48d46',
    authDomain: 'smartmart-48d46.firebaseapp.com',
    storageBucket: 'smartmart-48d46.appspot.com',
    measurementId: 'G-YQ6QR6L9V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPP2x6sCd1P-6oYgtoo6M5XynvnULh-P8',
    appId: '1:304338530315:android:1ba54e0c36b516e8e9570e',
    messagingSenderId: '304338530315',
    projectId: 'smartmart-48d46',
    storageBucket: 'smartmart-48d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5B9NR5QTlKyyBjapc8pu21-GfgkL9SbQ',
    appId: '1:304338530315:ios:31fb7a8ac1678c9be9570e',
    messagingSenderId: '304338530315',
    projectId: 'smartmart-48d46',
    storageBucket: 'smartmart-48d46.appspot.com',
    iosClientId: '304338530315-bulmdud8i1u4bmfdr3e842biboians5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5B9NR5QTlKyyBjapc8pu21-GfgkL9SbQ',
    appId: '1:304338530315:ios:a773ac440dad6438e9570e',
    messagingSenderId: '304338530315',
    projectId: 'smartmart-48d46',
    storageBucket: 'smartmart-48d46.appspot.com',
    iosClientId: '304338530315-j971eqj9f7oiv1l7t02kerd6bcjpaooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmart.RunnerTests',
  );
}
