/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Josep
 */
public class frmAgregar extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregar
     */
    PreparedStatement pr = null;
    ResultSet rs = null;
    conexionBD BD = new conexionBD();

    /**
     * Creates new form pnlAgregar
     */
    public frmAgregar() {
        
        initComponents();
        
        cmbArticulo.addItem("Seleccione un articulo");
        updateCmb();
    }

    private void updateCmb() {
        String sql = "SELECT descripcion FROM inventario_smartmart";

        try {
            pr = BD.conectar.prepareStatement(sql);
            rs = pr.executeQuery();

            // Agregar los elementos al JComboBox
            while (rs.next()) {
                cmbArticulo.addItem(rs.getString("descripcion"));
            }
        } catch (Exception e) {
            System.out.println("Error al agergar objeto: " + e.getMessage());
        }
    }

    public void obtenerCodigoArticulo(String idSeleccionado, JTextField txtCodigo) {

        // Consulta para obtener el nombre del artículo basado en el ID seleccionado
        String sql2 = "SELECT codigo FROM inventario_smartmart WHERE descripcion = ?";

        try {
            pr = BD.conectar.prepareStatement(sql2);
            pr.setString(1, idSeleccionado);
            rs = pr.executeQuery();

            // Mostrar el nombre del artículo en el JTextField
            if (rs.next()) {
                String nombreArticulo = rs.getString("codigo");
                txtCodigo.setText(nombreArticulo);
            }
        } catch (Exception e) {
            System.out.println("Error al obtener nombre del artículo: " + e.getMessage());
        }
    }
    
    
    public void obtenerCantidadActualArticulo(String idSeleccionado, JTextField txtCodigo) {

        // Consulta para obtener el nombre del artículo basado en el ID seleccionado
        String sql2 = "SELECT inventario FROM inventario_smartmart WHERE descripcion = ?";

        try {
            pr = BD.conectar.prepareStatement(sql2);
            pr.setString(1, idSeleccionado);
            rs = pr.executeQuery();

            // Mostrar el nombre del artículo en el JTextField
            if (rs.next()) {
                String nombreArticulo = rs.getString("inventario");
                txtCantidad.setText(nombreArticulo);
            }
        } catch (Exception e) {
            System.out.println("Error al obtener nombre del artículo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbArticulo = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtCantidadAgregar = new javax.swing.JTextField();
        btnMas = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTitulo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Articulo");

        jLabel2.setText("Codigo");

        Cantidad.setText("Cantidad Actual");

        jLabel4.setText("Cantidad a Agregar");

        cmbArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArticuloActionPerformed(evt);
            }
        });

        btnMas.setText("+");
        btnMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasMouseClicked(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosMouseClicked(evt);
            }
        });

        mnuTitulo.setText("Agregar Cantidad");
        jMenuBar1.add(mnuTitulo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbArticulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnSalir))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtCantidadAgregar.setEnabled(false);
        txtCantidadAgregar.setText(Integer.toString(0));

    }//GEN-LAST:event_formWindowOpened

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void cmbArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArticuloActionPerformed
        // TODO add your handling code here:
        String idSeleccionado = cmbArticulo.getSelectedItem().toString();
        
        obtenerCodigoArticulo(idSeleccionado, txtCodigo);
        obtenerCantidadActualArticulo(idSeleccionado, txtCantidad);
        
    }//GEN-LAST:event_cmbArticuloActionPerformed

    private void btnMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasMouseClicked
        // TODO add your handling code here:
        
        int valor = Integer.parseInt(txtCantidadAgregar.getText());
        valor +=1;
        
        txtCantidadAgregar.setText(Integer.toString(valor));
        
        
    }//GEN-LAST:event_btnMasMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        String valor = txtCantidadAgregar.getText();
        // Obtener la cantidad a agregar del JTextField
        int cantidadAAgregar = Integer.parseInt(txtCantidadAgregar.getText());
        // Obtener el valor seleccionado en el JComboBox
        String articuloSeleccionado = (String) cmbArticulo.getSelectedItem();
        if (valor.equals("0")) {
            JOptionPane.showMessageDialog(null, "No se pueden agregar 0 elementos");
        }else{
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de querer agregar " + valor +"?");
            
            if (respuesta == JOptionPane.YES_OPTION){
                String sql = "UPDATE inventario_smartmart SET inventario = inventario + ? WHERE descripcion = ?";
                try {
                    pr = BD.conectar.prepareStatement(sql);
                    pr.setInt(1, cantidadAAgregar);
                    pr.setString(2, articuloSeleccionado);
                    
                    int filasAfectadas = pr.executeUpdate();
                    if (filasAfectadas > 0) {
                        JOptionPane.showMessageDialog(null, "Cantidad actualizada en inventario correctamente");
                        txtCantidadAgregar.setText("0");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al actualizar la cantidad en inventario");
                    }
                } catch (Exception e) {
                    System.out.println("Error al actualizar la cantidad en inventario: " + e.getMessage());
                }
            }else{
                
            }
        }
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseClicked
         int valor = Integer.parseInt(txtCantidadAgregar.getText());
         
         if (valor <= 0){
             JOptionPane.showMessageDialog(null, "No se puede tener valores menores a 0");
         }else{
             valor -=1;
         }
         
        txtCantidadAgregar.setText(Integer.toString(valor));
    }//GEN-LAST:event_btnMenosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuTitulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadAgregar;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
